#! /bin/sh
### BEGIN INIT INFO
# Provides: pwrmanage
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: 
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
FILE_NAME="rpi_pwrdownisr_torex.py"
WORK_DIR="/home/ubuntu/pyspace/scp_torex_pwr_down_isr/"
ALLPATH="/home/ubuntu/pyspace/scp_torex_pwr_down_isr/rpi_pwrdownisr_torex.py"

case $1 in
  start)
	echo "pwrmanage dummy start"
  	;;

  stop)
	#cd $WORK_DIR
	python3 $ALLPATH
	echo "Python program is started"
	;;
  *)
	echo "hi"
	;;

esac

exit 0

